- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC vars
      include_vars: vars/vpc.yml

    - name: Create Ecommerce VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: true
        dns_hostnames: true
        tenancy: default
        state: "{{state}}"
      register: vpcout

#    - debug:
#        var: vpcout  

    - name: Create public subnet 1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        cidr: "{{PubSub1Cidr}}"
        state: "{{state}}"
        tags:
          Name: ecommerce-pubsub1
      register: pubsub1_out

    - name: Create public subnet 2 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        cidr: "{{PubSub2Cidr}}"
        state: "{{state}}"
        tags:
          Name: ecommerce-pubsub2
      register: pubsub2_out

    - name: Create public subnet 3 in zone3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        cidr: "{{PubSub3Cidr}}"
        state: "{{state}}"
        tags:
          Name: ecommerce-pubsub3
      register: pubsub3_out
