- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC vars
      include_vars: vars/vpc.yml

    - name: Create Ecommerce VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: true
        dns_hostnames: true
        tenancy: default
        state: "{{state}}"
      register: vpcout

    - debug:
        var: vpcout  

    - name: Create VPC subnets
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        cidr: "{{PubSub1Cidr}}"
        state: "{{state}}"
        tags:
          Name: ecommerce-pubsub1
      register: pubsub1_out
